# Utiliser l'image officielle Python
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier requirements.txt
COPY requirements.txt /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier l'application Flask
COPY . /app/

# Exposer le port de l'application Flask
EXPOSE 5001

# Lancer l'application Flask
CMD ["python", "app.py"]