version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Monter le dossier backend pour le live reload
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app  # Monter le dossier frontend pour le live reload
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge