version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge